name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 5 1,15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python: "3.6"
          - os: ubuntu-latest
            python: "3.7"
          - os: ubuntu-latest
            python: "3.8"
          - os: ubuntu-latest
            python: "3.9"
          - os: ubuntu-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.11"

    name: ${{ matrix.name }} Python ${{ matrix.python }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          pip install ${{ matrix.pip-flags }} ".[dev,test]"
      - name: Add conda to PATH
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Build dbCAN Database
        run: |
          conda install -y -c bioconda -c conda-forge hmmer diamond blast prodigal
          dbcan_build --cpus 1 --db-dir db --clean
      - name: Test
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42
        run: |
          coverage run -m pytest -v --color=yes
